<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class WorkTypeChecklistCriteriaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $criterias = [
            // Proyecto de Extensión (ID 1)
            [
                'work_type_id' => 1,
                'criteria_key' => 'project_title_concise',
                'name' => 'Título del proyecto conciso',
                'description' => 'El título establece de modo conciso el propósito del proyecto',
                'category' => 'datos_generales',
                'order' => 1,
                'is_required' => true,
            ],
            [
                'work_type_id' => 1,
                'criteria_key' => 'project_unit_defined',
                'name' => 'Unidad ejecutora definida',
                'description' => 'Se precisa la sede, facultad, departamento y unidad ejecutora',
                'category' => 'datos_generales',
                'order' => 2,
                'is_required' => true,
            ],
            [
                'work_type_id' => 1,
                'criteria_key' => 'project_responsible_participants_complete',
                'name' => 'Responsable y participantes completos',
                'description' => 'Señala nombre y datos del responsable principal y colaboradores, indicando su rol',
                'category' => 'datos_generales',
                'order' => 3,
                'is_required' => true,
            ],
            [
                'work_type_id' => 1,
                'criteria_key' => 'project_duration_dates_defined',
                'name' => 'Duración y fechas definidas',
                'description' => 'Especifica tiempo de duración con fecha de inicio y terminación',
                'category' => 'datos_generales',
                'order' => 4,
                'is_required' => true,
            ],
            [
                'work_type_id' => 1,
                'criteria_key' => 'project_general_description_complete',
                'name' => 'Descripción general completa',
                'description' => 'Indica elementos constitutivos, alcance total, componentes y resultados',
                'category' => 'descripcion_proyecto',
                'order' => 5,
                'is_required' => true,
            ],
            [
                'work_type_id' => 1,
                'criteria_key' => 'project_justification_adequate',
                'name' => 'Justificación adecuada',
                'description' => 'Señala importancia, estudios/diagnósticos que justifiquen la intervención',
                'category' => 'descripcion_proyecto',
                'order' => 6,
                'is_required' => true,
            ],
            [
                'work_type_id' => 1,
                'criteria_key' => 'project_objectives_general_specific',
                'name' => 'Objetivos generales y específicos',
                'description' => 'Define propósito general y propósitos concretos relacionados con actividades',
                'category' => 'descripcion_proyecto',
                'order' => 7,
                'is_required' => true,
            ],
            [
                'work_type_id' => 1,
                'criteria_key' => 'project_scope_defined',
                'name' => 'Alcance definido',
                'description' => 'Representa la totalidad del trabajo requerido para completar el proyecto',
                'category' => 'descripcion_proyecto',
                'order' => 8,
                'is_required' => true,
            ],
            [
                'work_type_id' => 1,
                'criteria_key' => 'project_resource_plan_complete',
                'name' => 'Plan de recursos completo',
                'description' => 'Especifica recursos materiales y humanos, quién los proporciona',
                'category' => 'descripcion_proyecto',
                'order' => 9,
                'is_required' => true,
            ],
            [
                'work_type_id' => 1,
                'criteria_key' => 'project_schedule_realistic',
                'name' => 'Cronograma realista',
                'description' => 'Asignación de tiempo a actividades con desglose detallado',
                'category' => 'descripcion_proyecto',
                'order' => 10,
                'is_required' => true,
            ],
            [
                'work_type_id' => 1,
                'criteria_key' => 'project_cost_plan_detailed',
                'name' => 'Plan de costos detallado',
                'description' => 'Indica costo valorizado por cada actividad planificada',
                'category' => 'descripcion_proyecto',
                'order' => 11,
                'is_required' => true,
            ],
            [
                'work_type_id' => 1,
                'criteria_key' => 'project_beneficiaries_described',
                'name' => 'Beneficiarios descritos',
                'description' => 'Señala quienes son los beneficiarios y cómo se benefician',
                'category' => 'descripcion_proyecto',
                'order' => 12,
                'is_required' => true,
            ],
            [
                'work_type_id' => 1,
                'criteria_key' => 'project_institution_relationships_clear',
                'name' => 'Relaciones institucionales claras',
                'description' => 'Indica alianzas con otros organismos oficiales o gubernamentales',
                'category' => 'descripcion_proyecto',
                'order' => 13,
                'is_required' => false,
            ],
            [
                'work_type_id' => 1,
                'criteria_key' => 'project_final_comments_relevant',
                'name' => 'Comentarios finales relevantes',
                'description' => 'Explica aspectos relevantes, recomendaciones y mejoras posibles',
                'category' => 'descripcion_proyecto',
                'order' => 14,
                'is_required' => false,
            ],

            // Actividad de Extensión (ID 2)
            [
                'work_type_id' => 2,
                'criteria_key' => 'activity_title_concise',
                'name' => 'Título de actividad conciso',
                'description' => 'El título establece de modo conciso el propósito de la actividad',
                'category' => 'datos_generales',
                'order' => 1,
                'is_required' => true,
            ],
            [
                'work_type_id' => 2,
                'criteria_key' => 'activity_unit_defined',
                'name' => 'Unidad ejecutora definida',
                'description' => 'Se precisa la sede, facultad, departamento y unidad ejecutora',
                'category' => 'datos_generales',
                'order' => 2,
                'is_required' => true,
            ],
            [
                'work_type_id' => 2,
                'criteria_key' => 'activity_responsible_participants_complete',
                'name' => 'Responsable y participantes completos',
                'description' => 'Señala nombre y datos del responsable principal y colaboradores',
                'category' => 'datos_generales',
                'order' => 3,
                'is_required' => true,
            ],
            [
                'work_type_id' => 2,
                'criteria_key' => 'activity_duration_dates_defined',
                'name' => 'Duración y fechas definidas',
                'description' => 'Especifica tiempo de duración con fecha de inicio y terminación',
                'category' => 'datos_generales',
                'order' => 4,
                'is_required' => true,
            ],
            [
                'work_type_id' => 2,
                'criteria_key' => 'activity_introduction_contextualized',
                'name' => 'Introducción contextualizada',
                'description' => 'Describe brevemente en qué consiste la actividad (taller, exposición, etc.)',
                'category' => 'descripcion_actividad',
                'order' => 5,
                'is_required' => true,
            ],
            [
                'work_type_id' => 2,
                'criteria_key' => 'activity_justification_adequate',
                'name' => 'Justificación adecuada',
                'description' => 'Incorpora aspectos que indiquen pertinencia y necesidad de la actividad',
                'category' => 'descripcion_actividad',
                'order' => 6,
                'is_required' => true,
            ],
            [
                'work_type_id' => 2,
                'criteria_key' => 'activity_objectives_general_specific',
                'name' => 'Objetivos generales y específicos',
                'description' => 'Define propósitos de la actividad',
                'category' => 'descripcion_actividad',
                'order' => 7,
                'is_required' => true,
            ],
            [
                'work_type_id' => 2,
                'criteria_key' => 'activity_methodology_detailed',
                'name' => 'Metodología detallada',
                'description' => 'Indica procedimientos para llevar a cabo la actividad',
                'category' => 'descripcion_actividad',
                'order' => 8,
                'is_required' => true,
            ],
            [
                'work_type_id' => 2,
                'criteria_key' => 'activity_duration_reasonable',
                'name' => 'Duración razonable',
                'description' => 'Indica tiempo global y desglosado dedicado a la actividad',
                'category' => 'descripcion_actividad',
                'order' => 9,
                'is_required' => true,
            ],
            [
                'work_type_id' => 2,
                'criteria_key' => 'activity_resources_available',
                'name' => 'Recursos disponibles',
                'description' => 'Determina recursos humanos y materiales con desglose y costos',
                'category' => 'descripcion_actividad',
                'order' => 10,
                'is_required' => true,
            ],
            [
                'work_type_id' => 2,
                'criteria_key' => 'activity_beneficiaries_profile_clear',
                'name' => 'Perfil de beneficiarios claro',
                'description' => 'Indica a qué población va dirigida y cómo se favorece',
                'category' => 'descripcion_actividad',
                'order' => 11,
                'is_required' => true,
            ],
            [
                'work_type_id' => 2,
                'criteria_key' => 'activity_supporting_document_complete',
                'name' => 'Documento de respaldo completo',
                'description' => 'Entrega texto completo que incorpore todos los elementos de la actividad',
                'category' => 'descripcion_actividad',
                'order' => 12,
                'is_required' => true,
            ],
            [
                'work_type_id' => 2,
                'criteria_key' => 'activity_institution_relationships_present',
                'name' => 'Relaciones institucionales presentes',
                'description' => 'Indica y explica alianzas con otras instituciones',
                'category' => 'descripcion_actividad',
                'order' => 13,
                'is_required' => false,
            ],
            [
                'work_type_id' => 2,
                'criteria_key' => 'activity_comments_relevant',
                'name' => 'Comentarios relevantes',
                'description' => 'Indica reflexiones, aspectos fuertes y débiles del desarrollo',
                'category' => 'descripcion_actividad',
                'order' => 14,
                'is_required' => false,
            ],

            // Publicación (ID 3)
            [
                'work_type_id' => 3,
                'criteria_key' => 'publication_title_present',
                'name' => 'Título de publicación presente',
                'description' => 'Indica el título con el que aparece publicada la obra',
                'category' => 'datos_publicacion',
                'order' => 1,
                'is_required' => true,
            ],
            [
                'work_type_id' => 3,
                'criteria_key' => 'publication_summary_comprehensive',
                'name' => 'Resumen comprehensivo',
                'description' => 'Presenta resumen completo de la publicación',
                'category' => 'datos_publicacion',
                'order' => 2,
                'is_required' => true,
            ],
            [
                'work_type_id' => 3,
                'criteria_key' => 'publication_relevance_justified',
                'name' => 'Relevancia justificada',
                'description' => 'Explica la importancia y necesidad de la publicación',
                'category' => 'datos_publicacion',
                'order' => 3,
                'is_required' => true,
            ],
            [
                'work_type_id' => 3,
                'criteria_key' => 'publication_date_valid',
                'name' => 'Fecha de publicación válida',
                'description' => 'Pertenece al semestre vigente para evaluación por resultados',
                'category' => 'datos_publicacion',
                'order' => 4,
                'is_required' => true,
            ],
            [
                'work_type_id' => 3,
                'criteria_key' => 'publication_media_type_appropriate',
                'name' => 'Tipo de medio apropiado',
                'description' => 'Especifica si es revista, prensa u otro medio',
                'category' => 'datos_publicacion',
                'order' => 5,
                'is_required' => true,
            ],
            [
                'work_type_id' => 3,
                'criteria_key' => 'publication_media_nature_clear',
                'name' => 'Naturaleza del medio clara',
                'description' => 'Indica si es especializada, indexada, etc.',
                'category' => 'datos_publicacion',
                'order' => 6,
                'is_required' => true,
            ],

            // Asistencia Técnica (ID 4)
            [
                'work_type_id' => 4,
                'criteria_key' => 'assistance_denomination_clear',
                'name' => 'Denominación de asistencia clara',
                'description' => 'Indica concretamente en qué consiste la intervención',
                'category' => 'datos_asistencia',
                'order' => 1,
                'is_required' => true,
            ],
            [
                'work_type_id' => 4,
                'criteria_key' => 'assistance_collaborating_institution_clear',
                'name' => 'Institución colaboradora clara',
                'description' => 'Especifica institución pública o privada que solicita el servicio',
                'category' => 'datos_asistencia',
                'order' => 2,
                'is_required' => true,
            ],
            [
                'work_type_id' => 4,
                'criteria_key' => 'assistance_description_comprehensive',
                'name' => 'Descripción comprehensiva',
                'description' => 'Indica elementos principales de la intervención',
                'category' => 'datos_asistencia',
                'order' => 3,
                'is_required' => true,
            ],
            [
                'work_type_id' => 4,
                'criteria_key' => 'assistance_objectives_clear',
                'name' => 'Objetivos claros',
                'description' => 'Define propósitos de la asistencia técnica',
                'category' => 'datos_asistencia',
                'order' => 4,
                'is_required' => true,
            ],
            [
                'work_type_id' => 4,
                'criteria_key' => 'assistance_methodology_detailed',
                'name' => 'Metodología detallada',
                'description' => 'Indica procedimientos para realizar la asistencia',
                'category' => 'datos_asistencia',
                'order' => 5,
                'is_required' => true,
            ],
            [
                'work_type_id' => 4,
                'criteria_key' => 'assistance_evidence_sufficient',
                'name' => 'Evidencias suficientes',
                'description' => 'Incluye nota de asignación, resumen y certificación de culminación',
                'category' => 'datos_asistencia',
                'order' => 6,
                'is_required' => true,
            ],
        ];

        foreach ($criterias as $criteria) {
            \App\Models\WorkTypeChecklistCriteria::updateOrCreate(
                [
                    'work_type_id' => $criteria['work_type_id'],
                    'criteria_key' => $criteria['criteria_key']
                ],
                $criteria
            );
        }

        echo "✓ Criterios de checklist por tipo de trabajo cargados\n";
        echo "📊 Total: " . count($criterias) . " criterios disponibles\n";
    }
}
